class TokenType
  SINGLE_CHAR = [
    :LEFT_PAREN, :RIGHT_PAREN, :LEFT_BRACE, :RIGHT_BRACE, :COMMA, :DOT, :MINUS, :PLUS, :SEMICOLON, :SLASH, :STAR
  ]

  ONE_OR_TWO_CHAR = [
    :BANG, :BANG_EQUAL, :EQUAL, :EQUAL_EQUAL, :GREATER, :GREATER_EQUAL, :LESS, :LESS_EQUAL
  ]

  LITERAL = [
    :IDENTIFIER, :STRING, :NUMBER
  ]

  KEYWORD = [
    :AND, :CLASS, :ELSE, :FALSE, :FUN, :FOR, :IF, :NIL, :OR, :PRINT, :RETURN, :SUPER, :THIS, :TRUE, :VAR, :WHILE, :EOF
  ]
end
